import { useState } from 'react';
import { Mail, MapPin, MessageCircle, Phone } from 'lucide-react';
import { Link } from 'react-router-dom';
import { LeadCapture } from '../components/LeadCapture';
import { PageIntro } from '../components/Cards';
import { SEO } from '../components/SEO';
import { contact, faqs, media, testimonials } from '../data/content';
import { analytics } from '../lib/analytics';
import { firebaseEnabled } from '../lib/firebase';
import { submissionRepository } from '../repositories/submissionRepository';

export function AboutPage() { return <><SEO title="About" description="Meet Popoola Adebola Opeyemi, founder of Tamlois Trichology Clinic." /><PageIntro title="Careful attention before a recommendation" text="Tamlois brings professional trichology and natural-hair care into one calm, personalised clinic experience." /><section className="section-space"><div className="container-shell grid items-center gap-12 lg:grid-cols-[.8fr_1.2fr]"><figure><img src={media.practitioner.src} alt={media.practitioner.alt} className="aspect-[4/5] w-full rounded-[14px] object-cover" /><figcaption className="mt-3 text-xs font-semibold text-[#8b4e22]">Licensed stock placeholder. This is not Popoola Adebola Opeyemi.</figcaption></figure><div><h2 className="section-title">Popoola Adebola Opeyemi</h2><p className="mt-6 text-xl leading-9 text-[var(--ink)]">Certified Trichologist, Natural Hair Advocate and Founder of Tamlois Trichology Clinic, passionate about healthy hair and scalp care.</p><p className="mt-6 max-w-2xl leading-7 text-[var(--muted)]">The clinic’s approach begins with listening, observing visible signs, reviewing the current routine and explaining suitable next steps. No additional qualifications, licences, memberships or years of practice have been assumed.</p><Link to="/booking?service=svc-consult" className="btn btn-primary mt-8">Book a consultation</Link></div></div></section><section className="section-space bg-[var(--cream)]"><div className="container-shell"><h2 className="section-title">The care principles</h2><div className="mt-9 grid gap-8 md:grid-cols-2"><div className="border-t border-[var(--line)] pt-5"><h3 className="font-display text-2xl">Understand first</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">A useful recommendation begins with a proper history and assessment.</p></div><div className="border-t border-[var(--line)] pt-5"><h3 className="font-display text-2xl">Explain clearly</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Clients should understand the purpose, limits and next step of their care.</p></div><div className="border-t border-[var(--line)] pt-5"><h3 className="font-display text-2xl">Refer when needed</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Clinic support does not replace a medical doctor or dermatologist.</p></div><div className="border-t border-[var(--line)] pt-5"><h3 className="font-display text-2xl">Make care workable</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">A routine should fit the client’s hair, scalp, schedule and resources.</p></div></div></div></section></>; }

export function ResultsPage() { return <><SEO title="Results" description="Consent-aware placeholder layouts for Tamlois client experiences and progress stories." /><PageIntro title="Progress is personal" text="This page demonstrates how real, consented client stories can be presented. It does not contain verified outcomes and does not promise regrowth." /><section className="section-space"><div className="container-shell grid gap-10 lg:grid-cols-[1.15fr_.85fr]"><div><img src={media.results.src} alt={media.results.alt} className="aspect-[16/10] w-full rounded-[14px] object-cover" /><div className="mt-5 rounded-[12px] bg-[var(--forest-50)] p-5 text-sm leading-6"><strong>Consent-aware before and after placeholder:</strong> Replace with matched lighting, angle, timeframe, written consent and honest context. Never imply a guaranteed result.</div></div><div className="rule-list">{testimonials.map((item) => <figure key={item.id} className="py-7"><blockquote className="font-display text-3xl leading-tight">“{item.quote}”</blockquote><figcaption className="mt-4 text-sm font-bold">{item.name}<span className="mt-1 block text-xs font-normal text-[#8b4e22]">{item.label}</span></figcaption></figure>)}</div></div></section></>; }

export function FAQPage() { return <><SEO title="Frequently asked questions" description="Answers about Tamlois consultations, booking, preparation and policies." schema={{ '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map(([question, answer]) => ({ '@type': 'Question', name: question, acceptedAnswer: { '@type': 'Answer', text: answer } })) }} /><PageIntro title="Questions before your appointment" text="Policy answers are placeholders until the clinic confirms final terms." /><section className="section-space"><div className="container-shell max-w-4xl rule-list">{faqs.map(([question, answer]) => <details key={question} className="group py-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-display text-2xl text-[var(--forest-950)]">{question}<span className="font-sans text-2xl group-open:rotate-45">+</span></summary><p className="mt-4 max-w-2xl leading-7 text-[var(--muted)]">{answer}</p></details>)}</div></section></>; }

export function ContactPage() {
  const [sent, setSent] = useState(false);
  const [error, setError] = useState('');
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); const data = new FormData(event.currentTarget); try { await submissionRepository.saveEnquiry({ id: crypto.randomUUID(), fullName: String(data.get('fullName') || ''), email: String(data.get('email') || ''), message: String(data.get('message') || ''), consent: data.get('consent') === 'on', createdAt: new Date().toISOString() }); setSent(true); } catch { setError('The enquiry could not be saved. Please retry.'); } }
  return <><SEO title="Contact" description="Contact Tamlois Naturals & Trichology Clinic." /><PageIntro title="Ask before you book" text={firebaseEnabled ? 'Tell us briefly what you have noticed. Your enquiry will be stored for the clinic; email delivery is configured separately.' : 'Tell us briefly what you have noticed. Demo enquiries stay in this browser until Firebase is configured.'} /><section className="section-space"><div className="container-shell grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div className="grid gap-4"><div className="surface flex gap-4 p-5"><MapPin className="text-[var(--forest-700)]" /><div><h2 className="font-bold">Clinic address</h2><p className="mt-1 text-sm text-[var(--muted)]">{contact.address}</p></div></div><a className="surface flex gap-4 p-5" href={`tel:${contact.phone}`} onClick={() => analytics.track('phone_clicked')}><Phone className="text-[var(--forest-700)]" /><div><h2 className="font-bold">Phone</h2><p className="mt-1 text-sm text-[var(--muted)]">{contact.phone}</p></div></a><a className="surface flex gap-4 p-5" href="#" onClick={() => analytics.track('whatsapp_clicked')}><MessageCircle className="text-[var(--forest-700)]" /><div><h2 className="font-bold">WhatsApp</h2><p className="mt-1 text-sm text-[var(--muted)]">{contact.whatsapp}</p></div></a><div className="surface flex gap-4 p-5"><Mail className="text-[var(--forest-700)]" /><div><h2 className="font-bold">Email</h2><p className="mt-1 text-sm text-[var(--muted)]">{contact.email}</p></div></div></div><div className="surface p-6 md:p-8">{sent ? <div role="status"><h2 className="font-display text-3xl">Enquiry saved</h2><p className="mt-3 leading-7 text-[var(--muted)]">{firebaseEnabled ? 'The clinic can review this enquiry in the configured project. A separate notification provider is required for email delivery.' : 'This demo enquiry exists only in this browser and was not sent to the clinic.'}</p></div> : <form className="grid gap-5" onSubmit={submit}><h2 className="font-display text-3xl">Send a short enquiry</h2><div className="field"><label htmlFor="contact-name">Full name</label><input id="contact-name" name="fullName" required /></div><div className="field"><label htmlFor="contact-email">Email</label><input id="contact-email" name="email" type="email" required /></div><div className="field"><label htmlFor="contact-message">How can we help?</label><textarea id="contact-message" name="message" minLength={5} required /></div><label className="flex items-start gap-3 text-sm leading-6"><input type="checkbox" name="consent" required className="mt-1 size-5 accent-[var(--forest-800)]" />I consent to the clinic using these details to respond.</label>{error && <p className="field-error" role="alert">{error}</p>}<button className="btn btn-primary justify-self-start">{firebaseEnabled ? 'Send enquiry' : 'Save demo enquiry'}</button></form>}</div></div></section><section className="pb-20"><div className="container-shell"><LeadCapture /></div></section></>;
}

export function LegalPage({ kind }: { kind: 'privacy' | 'terms' | 'cancellation' }) {
  const data = {
    privacy: ['Privacy notice', 'Placeholder legal copy. The live notice must identify the data controller, lawful basis, retention periods, processors, rights, contact route, cookies and international transfers. Demo records remain in this browser. Firebase records will be governed by the configured project and rules.'],
    terms: ['Website terms', 'Placeholder legal copy. Confirm the site terms, clinical boundaries, intellectual property, acceptable use, governing law, disclaimers and limitation language with qualified counsel before launch.'],
    cancellation: ['Cancellation and rescheduling policy', 'Placeholder policy. The demo assumes that clients contact the clinic at least 24 hours before an appointment. Confirm notice periods, deposits, refunds, late arrival, no-show and rescheduling rules before launch.']
  }[kind];
  return <><SEO title={data[0]} description={data[1]} /><PageIntro title={data[0]} text="This page is intentionally marked as placeholder content and must be legally reviewed before launch." /><section className="section-space"><article className="container-shell max-w-3xl"><span className="status placeholder-badge">Replace before launch</span><p className="mt-7 text-lg leading-8 text-[var(--ink)]">{data[1]}</p><h2 className="mt-12 font-display text-3xl">Questions</h2><p className="mt-4 leading-7 text-[var(--muted)]">Use the confirmed clinic email and privacy contact once supplied. Until then, do not rely on this text as legal advice.</p></article></section></>;
}

export function NotFoundPage() { return <><SEO title="Page not found" description="The requested Tamlois page could not be found." /><section className="section-space"><div className="container-shell text-center"><p className="font-display text-8xl text-[var(--forest-100)]">404</p><h1 className="mt-4 font-display text-4xl">This page is not in the care plan</h1><p className="mt-4 text-[var(--muted)]">The link may be old or incomplete.</p><Link to="/" className="btn btn-primary mt-7">Return home</Link></div></section></>; }
